= EKS deployment

This example shows how to deploy Tapir to EKS using IRSA ([IAM roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)), that allows cluster operators to map AWS IAM Roles to Kubernetes Service Accounts.

== Prerequisites

You need to have the following tools installed:
* [Terraform](https://www.terraform.io/downloads.html)

This example assumes that you have a working AWS account and that you have:

* set up an EKS cluster with RBAC enabled
  * [EKS getting started](https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html)
* configured `~/.kube/config` to access the cluster
  * [EKS create kubeconfig](https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html)
* EKS with [ALB Ingress Controller](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html) installed
* EKS with [external-dns](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/aws.md) installed

== Deploying

You can deploy the example by running the following commands:

[source,bash]
----
terraform init
terraform apply -var="hosted_zone_name=<top_level_domain>" -var="eks_oidc_issuer_url=<eks_oidc_issuer_url>"
----

[INFO]
====
The `hosted_zone_name` variable should be set to the top level domain of your hosted zone in Route53 E.g. if `hosted_zone_name=example.org`, Tapir will be exposed on `https://tapir.example.org`. The `eks_oidc_issuer_url` variable should be set to the OIDC issuer URL of your EKS cluster.
====

== Cleaning up

You can clean up the example by running the following commands:

[source,bash]
----
terraform destroy -var="hosted_zone_name=<top_level_domain>" -var="eks_oidc_issuer_url=<eks_oidc_issuer_url>"
----

