{{- if .Values.certificate.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  {{- with .Values.certificate.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  name: {{ include "tapir.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "tapir.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  commonName: {{ .Values.certificate.domain | quote }}
  dnsNames:
    - {{ .Values.certificate.domain | quote }}
    {{- range .Values.certificate.additionalHosts }}
    - {{ . | quote }}
    {{- end }}
  {{- with .Values.certificate.duration }}
  duration: {{ . | quote }}
  {{- end }}
  {{- with .Values.certificate.renewBefore }}
  renewBefore: {{ . | quote }}
  {{- end }}
  issuerRef:
    {{- with .Values.certificate.issuer.group }}
    group: {{ . | quote }}
    {{- end }}
    kind: {{ .Values.certificate.issuer.kind | quote }}
    name: {{ .Values.certificate.issuer.name | quote }}
  {{- with .Values.certificate.privateKey }}
  privateKey:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.certificate.usages }}
  usages:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}