apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if .Values.deployment.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  name: {{ template "tapir.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "tapir.labels" . | nindent 4 }}
spec:
  {{- with .Values.deployment.strategy }}
  strategy:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "tapir.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.deployment.podAnnotations }}
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "tapir.labels" . | nindent 8 }}
        {{- if .Values.deployment.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- if .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- if .Values.deployment.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      {{- end }}
      serviceAccountName: {{ include "tapir.serviceAccountName" . }}
      containers:
      - name: {{ include "tapir.name" . }}
        image: {{ .Values.deployment.image.repository }}:{{ include "tapir.defaultDeployTag" . }}
        imagePullPolicy: {{ .Values.deployment.image.imagePullPolicy }}
        env:
        {{- include "tapir.env" . | indent 8 }}
        {{- range $key, $value := .Values.deployment.extraEnv }}
        - name: {{ $key }}
          value: {{ $value }}
        {{- end }}
        {{- with .Values.deployment.envFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - name: server
          containerPort: {{ .Values.deployment.containerPort }}
        {{- with .Values.deployment.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.deployment.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.deployment.resources | nindent 10 }}
        {{- with .Values.deployment.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.deployment.lifecycle }}
        lifecycle:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $constraint := . }}
      - {{ toYaml $constraint | nindent 8 | trim }}
        {{- if not $constraint.labelSelector }}
        labelSelector:
          matchLabels:
            {{- include "tapir.selectorLabels" $ | nindent 12 }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- if .Values.deployment.hostNetwork }}
      hostNetwork: {{ .Values.deployment.hostNetwork }}
      {{- end }}
      {{- with .Values.deployment.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsPolicy: {{ .Values.deployment.dnsPolicy }}