apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  name: {{ include "tapir.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "tapir.labels" . | nindent 4 }}
  {{- if .Values.service.labels }}
  {{- toYaml .Values.service.labels | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: https
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.deployment.containerPort }}
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePortHttps }}
    {{- end }}
  selector:
    {{- include "tapir.selectorLabels" . | nindent 4 }}
{{- if eq .Values.service.type "LoadBalancer" }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs: {{ .Values.service.externalIPs }}
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
{{- end -}}
{{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
{{- end }}
{{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
{{- end }}