name: Test tool integrations

on:
  schedule:
    - cron: "0 05 * * *"
  push:
    branches:
      - main

jobs:
  tfsec-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.2
        with:
          soft_fail: true
          working_directory: ci/tfsec
          format: json
          additional_args: --out ci-scan.json